### ISSUE TITLE
Create "Adding a button" in "User interface" section

### ISSUE THREAD

**Issue by skymakerjaime** [skymakerstudio/dynamaker-docs#13]

**Comment by skymakerjaime** [comment]
> Jaime [5:56 PM]
> måste lägga till en thumbnail för att göra en item i min flyout. Hur kan man lägga till png eller använda glyphicon i thumbnail (röd linjen)
> 
> olof [8:19 AM]
> misstänker att det kan behövas en update av flyout, kan vara så att glyphicon inte funkar där. png funkar inte alls i dynamaker än
> 
> kriffe [8:28 AM]
> Går kanske att lösa med en dataurl?
> 
> olof [9:04 AM]
> kanske, men tveksamt om flyout är skriven så att det fungerar i dagsläget

**Comment by axelSkyMaker** [comment]
Yes good idea, should we have this bug in the studio?

**Comment by skymakerjaime** [comment]
Yes https://github.com/skymakerstudio/skystudio-front/issues/321
