### ISSUE TITLE
Explain how the RefPlane object works

### ISSUE THREAD

**Issue by kriffe** [skymakerstudio/dynamaker-docs#3]
Since the SKYMATH.RefPlane(...) is used throughout the platform we need some kind of introduction to the definition of how it works. Create a project in dynamaker with a visualization of the different settings (use flat extrude and perhaps som layout sketches to show how it rotates).

- How to create RefPlane
- How the different axises rotate when refPlane rotates (x' always parallell with xy and z' always pointing towards z axis)

Example sketch of coordinate axises
![image](https://user-images.githubusercontent.com/10418534/52866740-9db38780-313f-11e9-8baa-1824145ed729.png)

**Comment by skymakerjaime** [comment]
See https://github.com/skymakerstudio/dynamaker-docs/blob/190225_refplane/docs/ref-plane.md

**Comment by kriffe** [comment]
@skymakerjaime The illustrations looks very good. Theta is pointing towards the wrong axis however. We have defined it to negative y-axis to make angles 0 and 0 align the both coordinate systems

![image](https://user-images.githubusercontent.com/10418534/53553715-911b3000-3b3e-11e9-8df9-96f821fadd3d.png)

**Comment by kriffe** [comment]
The advanced user cases could also be replaced with SKYCAD.computeAngleTheta(...) and SKYCAD.computeAnglePhi( .. )

**Comment by skymakerjaime** [comment]
just to make sure, Is it Theta from the projection of the plane to the negative y-axis or the opposite?

**Comment by kriffe** [comment]
Yes that should be correct. Please try the computeAngleTheta call for different planes (on SKYCAD or SKYMATH)
