### ISSUE TITLE
Add boolean operations examples to geometry2D.md

### ISSUE THREAD

**Issue by kriffe** [skymakerstudio/dynamaker-docs#4]
Add skysketch boolean examples to the geometry2D file. Also add image with two rectangles showing how each case works

- SKYSKETCH.generateSketchUnion(sketchA, sketchB)
- SKYSKETCH.generateSketchSubtraction(sketchA, sketchB)
- SKYSKETCH.generateSketchIntersection(sketchA, sketchB)

**Comment by skymakerjaime** [comment]
Result in docs:
![image](https://user-images.githubusercontent.com/36928972/53491208-1d254d00-3a96-11e9-81e4-df6b3569e6d9.png)
