### ISSUE TITLE
Explain the componentHandler in the studio

### ISSUE THREAD

**Issue by kriffe** [skymakerstudio/dynamaker-docs#5]
Create document and add explanation of how the componentHandler works

- How to create a component
- How to add a component
- How to get a component
- How the position and instance works with components

**Comment by skymakerjaime** [comment]
We can start from what @skymakerolof wrote in the handbook https://github.com/skymakerstudio/skystudio-handbook/wiki/Component-Handler

**Comment by skymakerjaime** [comment]
I would like to add the batteryholder app as an example after fixing https://github.com/skymakerstudio/skycad/issues/78

**Comment by axelSkyMaker** [comment]
Sounds good to me, I think we can use images from the current state of the application for now and replace with better resolution later (as we said on phone).

**Comment by skymakerjaime** [comment]
Done
