### ISSUE TITLE
Organise the starting page in an intuitive way

### ISSUE THREAD

**Issue by kriffe** [skymakerstudio/dynamaker-docs#8]
Go through index file and update for a good first order of the documentation

**Comment by axelSkyMaker** [comment]
Current order

![image](https://user-images.githubusercontent.com/24889873/55081695-a2ede580-50a0-11e9-9d37-33d1a2eb72a9.png)

I'm closing this issue. We'll open a new issue when we have a more precise change request.

**Comment by axelSkyMaker** [comment]
Changed my mind. We can discuss in this thread instead

**Comment by skymakerjaime** [comment]
I think we should a main page with all main sections, kind of to avoid the boring documentation format.
![image](https://user-images.githubusercontent.com/36928972/56959181-e5498d00-6b4c-11e9-946f-878efc5ed81b.png)

As an inspiration from Onshape (of what they call the Learning Center):
![image](https://user-images.githubusercontent.com/36928972/56959206-f6929980-6b4c-11e9-9690-5f030694a7ad.png)

**Comment by kriffe** [comment]
Good enoguh for now
