### ISSUE TITLE
Determine how to add and show images in the docs

### ISSUE THREAD

**Issue by kriffe** [skymakerstudio/dynamaker-docs#9]
How should we work with image files in the docs repo for them to publish correclty? Separate folder? Mixed in with the rest of the code.

Discuss and set a first strategy for everyone to work with.

**Comment by skymakerolof** [comment]
Static assets such as images should be placed in `docs/assets` and can then be linked from markdown files using this syntax:
```markdown
![alt-text](assets/image.png)
```
